name: Update Visitor Counter

on:
  workflow_dispatch:   # manual trigger only (run from Actions tab)

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Increment visitor count
        run: |
          file=data/visitors.json
          count=$(jq '.visitors += 1' "$file")
          echo "$count" > "$file"

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/visitors.json
          git commit -m "Update visitor count" || echo "No change"
          git push
